ML_VIDEO_DATA = [{'id': 1,
  'title': 'Data Science & Machine Learning Overview - Overview Video 1',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/DwqbxP5BDFo',
  'reference': '',
  'code': '',
  'dataset': 'https://bekushal.medium.com/curated-machine-learning-datasets-for-college-students-ba8cfbc98b6b',
  'imageUrl': 'https://img.youtube.com/vi/DwqbxP5BDFo/hqdefault.jpg'},
 {'id': 2,
  'title': 'Data Science & Machine Learning Overview - Overview Video 2',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/UnjyNYco7uQ',
  'reference': '',
  'code': '',
  'dataset': 'https://bekushal.medium.com/curated-machine-learning-datasets-for-college-students-ba8cfbc98b6b',
  'imageUrl': 'https://img.youtube.com/vi/UnjyNYco7uQ/hqdefault.jpg'},
 {'id': 3,
  'title': 'Random Variables and Probability Distributions - Random Variables & Probability',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/rGYqfhmdEmo',
  'reference': '',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/rGYqfhmdEmo/hqdefault.jpg'},
 {'id': 4,
  'title': 'Expectation, Moments and CLT - Expectation, Moments, CLT',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/3-A2siEN8w8',
  'reference': 'https://www.youtube.com/watch?v=JNm3M9cqWyc',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/3-A2siEN8w8/hqdefault.jpg'},
 {'id': 5,
  'title': "Bayes' Theorem - Bayes' Theorem Explained",
  'status': 'not-started',
  'youtubeLink': 'https://www.youtube.com/watch?v=q0p6VWj8N4I',
  'reference': 'https://www.mathsisfun.com/data/probability-events-conditional.html',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/q0p6VWj8N4I/hqdefault.jpg'},
 {'id': 6,
  'title': "Naïve Bayes, Gaussian Naive Bayes, Bayes' Optimal Classifier - Naive Bayes Introduction",
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/DV3F7AZOAE0',
  'reference': 'https://www.youtube.com/watch?v=O2L2Uv9pdDA',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/DV3F7AZOAE0/hqdefault.jpg'},
 {'id': 7,
  'title': 'Supervised Learning: Regression vs Classification, Curse of Dimensionality - Regression vs Classification',
  'status': 'not-started',
  'youtubeLink': 'https://www.youtube.com/watch?v=NYJZDRRUO84',
  'reference': 'https://in.springboard.com/blog/regression-vs-classification-in-machine-learning/',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/NYJZDRRUO84/hqdefault.jpg'},
 {'id': 8,
  'title': 'Bayesian Parameter Estimation - Bayesian Parameter Estimation',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/8P7tdwFF0is',
  'reference': '',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/8P7tdwFF0is/hqdefault.jpg'},
 {'id': 9,
  'title': 'Maximum Likelihood Estimation - Maximum Likelihood Estimation',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/WIPUh9yWM4c',
  'reference': 'https://allenkunle.me/deriving-ml-cost-functions-part1',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/WIPUh9yWM4c/hqdefault.jpg'},
 {'id': 10,
  'title': 'Maximum A Posteriori Estimation - Maximum A Posteriori Estimation',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/XKkfIU8ugjM',
  'reference': 'https://towardsdatascience.com/mle-vs-map-a989f423ae5c',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/XKkfIU8ugjM/hqdefault.jpg'},
 {'id': 11,
  'title': 'Supervised Learning: Gradient Descent & Regularisation - Gradient Descent & Regularisation',
  'status': 'not-started',
  'youtubeLink': 'https://www.youtube.com/watch?v=IUmFzIU-Cp4',
  'reference': 'https://towardsdatascience.com/gradient-descent-the-learning-rate-and-the-importance-of-feature-scaling-6c0b416596e1',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/IUmFzIU-Cp4/hqdefault.jpg'},
 {'id': 12,
  'title': 'Linear Regression: Normal Equation & Regularisation - Linear Regression Part 1',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/BGiAcoU4yWk',
  'reference': 'https://machinelearningmastery.com/linear-regression-for-machine-learning/',
  'code': 'https://inria.github.io/scikit-learn-mooc/python_scripts/linear_models_regularization.html',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/BGiAcoU4yWk/hqdefault.jpg'},
 {'id': 13,
  'title': 'Linear Regression: Normal Equation & Regularisation - Linear Regression Part 2',
  'status': 'not-started',
  'youtubeLink': 'https://www.youtube.com/watch?v=VqKq78PVO9g',
  'reference': 'https://machinelearningmastery.com/linear-regression-for-machine-learning/',
  'code': 'https://inria.github.io/scikit-learn-mooc/python_scripts/linear_models_regularization.html',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/VqKq78PVO9g/hqdefault.jpg'},
 {'id': 14,
  'title': 'Logistic Regression: Loss Function, Convexity, Gradient Descent - Logistic Regression Intro',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/sxaYUg6zc7I',
  'reference': 'https://activewizards.com/blog/5-real-world-examples-of-logistic-regression-application',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/sxaYUg6zc7I/hqdefault.jpg'},
 {'id': 15,
  'title': 'Logistic Regression: Multiclass Classification - Multiclass Logistic Regression',
  'status': 'not-started',
  'youtubeLink': 'https://www.youtube.com/watch?v=E6MNiNsESl4',
  'reference': 'https://web.stanford.edu/~jurafsky/slp3/5.pdf',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/E6MNiNsESl4/hqdefault.jpg'},
 {'id': 16,
  'title': 'Support Vector Machines with Linear Kernel - SVM with Linear Kernel',
  'status': 'not-started',
  'youtubeLink': 'https://www.youtube.com/watch?v=KvIdyz0KdCU',
  'reference': 'https://medium.com/@rinu.gour123/8-unique-real-life-applications-of-svm-8a96ca43313',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/KvIdyz0KdCU/hqdefault.jpg'},
 {'id': 17,
  'title': 'Support Vector Machines: Slack Variables and Nonlinear Kernels - SVM Slack & Nonlinear Kernels',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/kPuHAK4RCfM',
  'reference': 'http://openclassroom.stanford.edu/MainFolder/DocumentPage.php?course=MachineLearning&doc=exercises/ex8/ex8.html',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/kPuHAK4RCfM/hqdefault.jpg'},
 {'id': 18,
  'title': 'Decision Trees - Decision Trees Intro',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/OlreMWwTJ_8',
  'reference': 'https://www.youtube.com/watch?v=7VeUPuFGJHk',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/OlreMWwTJ_8/hqdefault.jpg'},
 {'id': 19,
  'title': 'Random Forest + Comparison of Trees, SVM & LogisticRegression - Random Forest & Comparisons',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/pEFBH_371sU',
  'reference': 'https://www.youtube.com/watch?v=4EOCQJgqAOY',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/pEFBH_371sU/hqdefault.jpg'},
 {'id': 20,
  'title': 'Artificial Neural Networks: Introduction - ANN Introduction',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/6nkylSKqaAc',
  'reference': 'http://neuralnetworksanddeeplearning.com/chap4.html',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/6nkylSKqaAc/hqdefault.jpg'},
 {'id': 21,
  'title': 'Artificial Neural Networks: Backpropagation - ANN Backpropagation',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/ntnwjWEpnkk',
  'reference': 'http://neuralnetworksanddeeplearning.com/chap2.html',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/ntnwjWEpnkk/hqdefault.jpg'},
 {'id': 22,
  'title': 'Artificial Neural Networks: Activation Functions, Loss functions & Optimization Algorithms - ANN Activation, Loss, Optimization',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/qctUEQn9Hj8',
  'reference': 'https://towardsdatascience.com/comparison-of-activation-functions-for-deep-neural-networks-706ac4284c8a',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/qctUEQn9Hj8/hqdefault.jpg'},
 {'id': 23,
  'title': 'Solving ODEs using ANN - ANN for ODEs',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/-pMLqoMarEk',
  'reference': 'https://www.sciencedirect.com/science/article/pii/S0021999118307125',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/-pMLqoMarEk/hqdefault.jpg'},
 {'id': 24,
  'title': 'Deep Learning (Introduction) - Deep Learning Intro Video',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/MTbBOu4M7_M',
  'reference': 'http://yann.lecun.com/exdb/mnist/',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/MTbBOu4M7_M/hqdefault.jpg'},
 {'id': 25,
  'title': 'Generative Vs. Discriminative Models - Generative vs Discriminative',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/WSxUOIGuGi8',
  'reference': '',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/WSxUOIGuGi8/hqdefault.jpg'},
 {'id': 26,
  'title': 'Probabilistic Graphical Models: Bayesian Network and Markov Network - PGM Intro Video 1',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/xJtyVQMV1A8',
  'reference': 'https://www.cs.ubc.ca/~murphyk/Bayes/bnintro.html',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/xJtyVQMV1A8/hqdefault.jpg'},
 {'id': 27,
  'title': 'Probabilistic Graphical Models: Bayesian Network and Markov Network - PGM Intro Video 2 (Expectation Maximization related)',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/PNrghbfK5r0',
  'reference': 'https://www.cs.ubc.ca/~murphyk/Bayes/bnintro.html',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/PNrghbfK5r0/hqdefault.jpg'},
 {'id': 28,
  'title': 'Expectation Maximization - Expectation Maximization1',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/PNrghbfK5r0',
  'reference': 'https://www.nature.com/articles/nbt1406',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/PNrghbfK5r0/hqdefault.jpg'},
 {'id': 29,
  'title': 'K-Means clustering - K-Means Clustering',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/92-h3_1Yfz8',
  'reference': 'https://becominghuman.ai/comprehending-k-means-and-knn-algorithms-c791be90883d',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/92-h3_1Yfz8/hqdefault.jpg'},
 {'id': 30,
  'title': 'Gaussian Mixture Models - Gaussian Mixture Models',
  'status': 'not-started',
  'youtubeLink': 'https://www.youtube.com/watch?v=he4lI0w1G-g',
  'reference': 'https://brilliant.org/wiki/gaussian-mixture-model/',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/he4lI0w1G-g/hqdefault.jpg'},
 {'id': 31,
  'title': 'Principal Component Analysis (PCA) - I - PCA Part 1',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/cERNIfg9TLM',
  'reference': 'https://builtin.com/data-science/step-step-explanation-principal-component-analysis',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/cERNIfg9TLM/hqdefault.jpg'},
 {'id': 32,
  'title': 'Principal Component Analysis (PCA) - II - PCA Part 2',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/ml1d1zC0jsg',
  'reference': 'https://shankarmsy.github.io/posts/pca-vs-lr.html',
  'code': 'https://shankarmsy.github.io/posts/pca-sklearn.html',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/ml1d1zC0jsg/hqdefault.jpg'},
 {'id': 33,
  'title': 'Reinforcement Learning - Reinforcement Learning Intro',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/KEQhaBIZ9yk',
  'reference': '',
  'code': 'https://amunategui.github.io/reinforcement-learning/index.html',
  'dataset': 'https://www.kaggle.com/code/nelver/rock-paper-scissors-q-learning',
  'imageUrl': 'https://img.youtube.com/vi/KEQhaBIZ9yk/hqdefault.jpg'},
 {'id': 34,
  'title': 'Reinforcement Learning - RL by Alexander Amini (YouTube)',
  'status': 'not-started',
  'youtubeLink': 'https://www.youtube.com/watch?v=nZfaHlxDD5w&ab_channel=AlexanderAmini',
  'reference': '',
  'code': 'https://amunategui.github.io/reinforcement-learning/index.html',
  'dataset': 'https://www.kaggle.com/code/nelver/rock-paper-scissors-q-learning',
  'imageUrl': 'https://img.youtube.com/vi/nZfaHlxDD5w/hqdefault.jpg'},
 {'id': 35,
  'title': 'Reinforcement Learning - RL Playlist 1 (YouTube)',
  'status': 'not-started',
  'youtubeLink': 'https://www.youtube.com/watch?v=zdIQkjtFX_I&list=PLKnIA16_RmvbMK0_fdp0DZHZKm4Q1sIAB',
  'reference': '',
  'code': 'https://amunategui.github.io/reinforcement-learning/index.html',
  'dataset': 'https://www.kaggle.com/code/nelver/rock-paper-scissors-q-learning',
  'imageUrl': 'https://img.youtube.com/vi/zdIQkjtFX_I/hqdefault.jpg'},
 {'id': 36,
  'title': 'Reinforcement Learning - RL Playlist 2 (YouTube)',
  'status': 'not-started',
  'youtubeLink': 'https://www.youtube.com/watch?v=WO3kmx4CVgg&list=PLycckD1ec_yNMjDI-Lq4-1ZqHcXqgm7',
  'reference': '',
  'code': 'https://amunategui.github.io/reinforcement-learning/index.html',
  'dataset': 'https://www.kaggle.com/code/nelver/rock-paper-scissors-q-learning',
  'imageUrl': 'https://img.youtube.com/vi/WO3kmx4CVgg/hqdefault.jpg'},
 {'id': 37,
  'title': 'Reinforcement Learning - RL Playlist 3 (YouTube)',
  'status': 'not-started',
  'youtubeLink': 'https://www.youtube.com/watch?v=yMk_XtIEzH8&list=PLQVvvaa0QuDezJFIOU5wDdfy4e9vdnx-7',
  'reference': '',
  'code': 'https://amunategui.github.io/reinforcement-learning/index.html',
  'dataset': 'https://www.kaggle.com/code/nelver/rock-paper-scissors-q-learning',
  'imageUrl': 'https://img.youtube.com/vi/yMk_XtIEzH8/hqdefault.jpg'},
 {'id': 38,
  'title': 'Reinforcement Learning - RL - L8ypSXwyBds (YouTube)',
  'status': 'not-started',
  'youtubeLink': 'https://www.youtube.com/watch?v=L8ypSXwyBds',
  'reference': '',
  'code': 'https://amunategui.github.io/reinforcement-learning/index.html',
  'dataset': 'https://www.kaggle.com/code/nelver/rock-paper-scissors-q-learning',
  'imageUrl': 'https://img.youtube.com/vi/L8ypSXwyBds/hqdefault.jpg'},
 {'id': 39,
  'title': 'Reinforcement Learning - RL - ovlykchkW5I (YouTube)',
  'status': 'not-started',
  'youtubeLink': 'https://www.youtube.com/watch?v=ovlykchkW5I&t=1s',
  'reference': '',
  'code': 'https://amunategui.github.io/reinforcement-learning/index.html',
  'dataset': 'https://www.kaggle.com/code/nelver/rock-paper-scissors-q-learning',
  'imageUrl': 'https://img.youtube.com/vi/ovlykchkW5I/hqdefault.jpg'},
 {'id': 40,
  'title': 'Reinforcement Learning - RL - 2eeYqJ0uBKE (YouTube)',
  'status': 'not-started',
  'youtubeLink': 'https://www.youtube.com/watch?v=2eeYqJ0uBKE',
  'reference': '',
  'code': 'https://amunategui.github.io/reinforcement-learning/index.html',
  'dataset': 'https://www.kaggle.com/code/nelver/rock-paper-scissors-q-learning',
  'imageUrl': 'https://img.youtube.com/vi/2eeYqJ0uBKE/hqdefault.jpg'},
 {'id': 41,
  'title': 'Big data technologies & Information management in Big Data - Big Data & Info Management',
  'status': 'not-started',
  'youtubeLink': 'https://youtu.be/5dSmXcKsEBo',
  'reference': 'https://www.edureka.co/blog/top-big-data-technologies/',
  'code': '',
  'dataset': '',
  'imageUrl': 'https://img.youtube.com/vi/5dSmXcKsEBo/hqdefault.jpg'}]